#!/opt/rubies/2.1.2/bin/ruby
# coding: BINARY
require "socket"
require "fileutils"
require "timeout"

$stdout.sync = true

instance_root = "/var/win95/instances/#{$$}"

begin
  Dir.mkdir(instance_root)

  FileUtils.cp("/var/win95/hdd.img", "#{instance_root}/hdd.img")

  qemu_pid = spawn "/usr/bin/qemu-system-i386",
    "-hda", "#{instance_root}/hdd.img",
    "-net", "none",
    "-nographic",
    "-vnc", "unix:#{instance_root}/vnc.sock",
    "-m", "16"

  Timeout.timeout(1) do
    until File.exist?("#{instance_root}/vnc.sock")
      sleep 0.05
    end
  end

  sock = UNIXSocket.new("#{instance_root}/vnc.sock")

  loop do
    read_ready, _, errored = IO.select([$stdin, sock], [])

    if errored.any?
      break
    end

    if read_ready.include?($stdin)
      sock.write($stdin.readpartial(4096))
    end

    if read_ready.include?(sock)
      $stdout.write(sock.readpartial(4096))
      $stdout.flush
    end
  end
ensure
  Process.kill(:KILL, qemu_pid) if qemu_pid
  FileUtils.rm_rf(instance_root)
end
