#!/opt/rubies/2.1.2/bin/ruby
require "digest/sha2"

AUTH_TOKEN_SHA2 = "df89efaba5da68f47c16fb71703b4816a9591cf63a44ddc509568afdabedf405" # call the cops

if Digest::SHA2.hexdigest(ENV["HTTP_X_AUTH_TOKEN"] || "") != AUTH_TOKEN_SHA2
  print "Status: 400\r\n" +
        "Content-Type: text/html\r\n" +
        "\r\n" +
        "<h1>nope</h1>"
  exit
end

target_filename = ENV["HTTP_X_FILENAME"]

target_path = "/var/www/charlie.su/#{target_filename}"

File.open(target_path, "w") do |f|
  IO.copy_stream($stdin, f)
end

if target_filename.end_with?(".jpg")
  system "/usr/bin/exiftool", "-q", "-all=", target_path
end

print "Status: 201\r\n" +
      "Content-Type: text/plain\r\n" +
      "\r\n" +
      "https://charlie.su/#{target_filename}"
